### PR TITLE
UADS-025 completed branch with all the typescript and mongoose functi…

### PR DESCRIPTION
**Pull request by Brendan-Z**
**Issue:**
As we're using typescript in conjunction with mongoose, typescript interfaces are needed to describe the mongoose schemas.

**Solution:**
Implemented typescript interfaces that allow the description of the mongoose schemas.

**Risk:**
There may be some errors in terms of the schema as we could not test on this specific branch. 

**Reviewed By:**
@serenalau272, @johnchen383, @Dan1224444

### CODE REVIEW

**Review by johnchen383 — DISMISSED** [review]
lgtm

**Review by Dan1224444 — CHANGES_REQUESTED** [review]
Please make sure the Interfaces match the mongoose schemas, as well as optional fields

**Comment by Brendan-Z** [comment]
Viewed the change and request and made changes accordingly :)

**Review by johnchen383 — DISMISSED** [review]
LGTM. Both userSchema.ts and Entities.ts look fine in terms of the defined schema. So should rebase well with 012. Not too sure about some of what's included in the other schemas but those can be modified I expect as those backend functions are authored.

**Review by serenalau272 — APPROVED** [review]
Looks good! userSchema.ts (and Entities.ts) has been defined well and fits with the backend functions already defined for users in 012 so should integrate well.

**Review by Dan1224444 — APPROVED** [review]
Looks good! thanks for the changes

**Review by johnchen383 — APPROVED** [review]
Looks good!! No errors when running on Linux VM so its promising. Third times the charm ahah.

**Pull request merged**
