### PR TITLE
Uads 031/husky hook

### PR DESCRIPTION
**Pull request by johnchen383**
**Issue:**
Commits to repositories were not properly formatted by prettier. 

**Solution:**
Husky and Lintstage were added to add a pre-commit hook to format commits prior to Git commits

**Risk:**
No risks of note. Would require review to ensure package.json works as required.

**Reviewed By:**
Backend: @Dan1224444 @Brendan-Z @serenalau272

### CODE REVIEW

**Comment by Dan1224444** [comment]
Have you tried this method?

https://github.com/azz/pretty-quick

**Comment by johnchen383** [comment]
> Have you tried this method?
> 
> https://github.com/azz/pretty-quick

Nope. But lintstage seems to work fine? It was from that link you sent me: https://dev.to/botreetechnologies/setting-up-husky-pre-commit-hook-with-eslint-prettier-and-lint-staged-for-react-and-react-native-d05

**Comment by Dan1224444** [comment]
It took me sometime to get it to work, I needed to `npx husky install` followed by `chmod ug+x .husky/*` and `chmod ug+x .git/hooks/*` 

It would be great if there was a command like `yarn run husky-init` which did all this for me :)

**Comment by johnchen383** [comment]
> It took me sometime to get it to work, I needed to `npx husky install` followed by `chmod ug+x .husky/*` and `chmod ug+x .git/hooks/*`
> 
> It would be great if there was a command like `yarn run husky-init` which did all this for me :)

Done :) Thanks for that!

**Review by Dan1224444 — APPROVED** [review]
LGTM !

**Review by serenalau272 — APPROVED** [review]
LGTM!

**Review by Brendan-Z — CHANGES_REQUESTED** [review]
243650006_558761965394250_5502441213804722865_n

NO IDEA WHATS WRONG BUT YEAH :(

**Review by Brendan-Z — APPROVED** [review]
nvm i was trolling

**Pull request merged**
