### PR TITLE
Finished About Page

### PR DESCRIPTION
**Pull request by Harsheel12**
**Issue:**
https://uads.atlassian.net/browse/U2-9

**Solution:**
Redesigned Front End About Page to match Figma.

**Risk:**
Potential conflict with menu button. As of this message, there is a white menu bar that obscures the social media bar. The white bar is to be replaced in a later branch.

**Reviewed By:**

### CODE REVIEW

**Review by avikash-naidu — CHANGES_REQUESTED** [review]
image
image
image

Web page components look disproportional to the figma design and mobile view try adding a media query for the page width to be narrower to see how it would look and let me know and please fill in the PR form using the Jira ticket

**Comment by khir829** [comment]
Mobile view:
image

Web page view:
image

In both cases, I assumed there should be no scrolling required to view the entire About page. 
I also assumed that the white 'menu' bar at the bottom is going to be scrapped in a later branch(?)

@avikash-naidu Can you please check if this is okay?

**Comment by khir829** [comment]
Latest commit changes cupcake image size to make it look more similar to the figma design.

Mobile
image

Web browser: standard 1080 x 1920
image

Figma
image

**Review by avikash-naidu — APPROVED** [review]
Will need to improve responsive in another ticket but the code looks good

**Pull request merged**
