### PR TITLE
Uads 011/express openapi validator

### PR DESCRIPTION
**Pull request by Dan1224444**
**Issue:**
Apicurio was not set up correctly to be used with swagger-routes-express and express-openapi-validator. 

**Solution:**
Create a script to download the API file from apicurio to transform it into a YAML file to be used. Routes and controllers have also been set up for get /event

**Risk:**
The script relies on Apicurio to be up and working for download

**Reviewed By:**
@johnchen383  @Brendan-Z

### CODE REVIEW

**Comment by johnchen383** [comment]
Looks good ahah

**Comment by Brendan-Z** [comment]
LGTM

**Review by johnchen383 — APPROVED** [review]
Looks gooddd

**Review by Brendan-Z — APPROVED** [review]
LGTM

**Pull request merged**
